ros_bridge:
    ros__parameters:
      topics: [{"topic": "/chatter", "type": "std_msgs/msg/String", "queue_size": "2"}]
        # some_int: 42
        # a_string: "Hello world"
        # some_lists:
        #     some_integers: [1, 2, 3, 4]
        #     some_doubles : [3.14, 2.718]`